version: '3.8'

services:

  db:
    image: postgres
    env_file: 
      - database.env
    ports:
      - "2345:5432"
    networks:
      - postgresql
    volumes:
      - ./schema:/docker-entrypoint-initdb.d

networks:
  postgresql:
    driver: bridge