-- add create db, user and permissions...

DROP SCHEMA IF EXISTS sys CASCADE;
DROP SCHEMA IF EXISTS product CASCADE;
DROP SCHEMA IF EXISTS inventory CASCADE;
DROP SCHEMA IF EXISTS financial CASCADE;
DROP SCHEMA IF EXISTS production CASCADE;
DROP SCHEMA IF EXISTS sales CASCADE;
DROP SCHEMA IF EXISTS purchase CASCADE;

CREATE SCHEMA sys;
CREATE SCHEMA product;
CREATE SCHEMA inventory;
CREATE SCHEMA financial;
CREATE SCHEMA production;
CREATE SCHEMA sales;
CREATE SCHEMA purchase;
