DROP SCHEMA IF EXISTS sys CASCADE;
DROP SCHEMA IF EXISTS inv CASCADE;
DROP SCHEMA IF EXISTS fin CASCADE;
DROP SCHEMA IF EXISTS prd CASCADE;

CREATE SCHEMA sys;
CREATE SCHEMA inv;
CREATE SCHEMA fin;
CREATE SCHEMA prd;