CREATE TABLE sys.login (
    id INTEGER GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50),
    middle_name VARCHAR(50),
    last_name_1 VARCHAR(50),
    last_name_2 VARCHAR(50),
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    password VARCHAR(100),
    is_active BOOL,
    can_login BOOL
);

CREATE TABLE sys.communication (
    id INTEGER GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
    name varchar(20)
);

-- DATA
INSERT INTO sys.communication(name) VALUES ('Email');
INSERT INTO sys.communication(name) VALUES ('Telefono');
INSERT INTO sys.communication(name) VALUES ('WhatsApp');
INSERT INTO sys.communication(name) VALUES ('Instagram');
INSERT INTO sys.communication(name) VALUES ('Facebook');
